title: WoukieNet | Blue Oasis 2025
email: admin@woukie.net
description: >-
  Archive and project list. Personal site. Not a blog.
baseurl: ""
url: ""
twitter_username: woukie
github_username:  woukie

theme: minima
plugins:
  - jekyll-feed
